export const AVATAR_OPTIONS = {
  top: [
    'longHair',
    'shortHair',
    'eyepatch',
    'hat',
    'hijab',
    'turban',
    'winterHat1',
    'winterHat2',
    'bigHair',
    'bob',
    'bun',
    'curly',
    'curvy',
    'dreads',
    'frida',
    'fro',
    'froBand',
    'miaWallace',
    'shavedSides',
    'straight01',
    'straight02',
    'straightStrand',
  ],
  accessories: [
    'none',
    'kurt',
    'prescription01',
    'prescription02',
    'round',
    'sunglasses',
    'wayfarers',
  ],
  hairColor: [
    'aurora',
    'black',
    'blonde',
    'blondeGolden',
    'brown',
    'brownDark',
    'pastelPink',
    'platinum',
    'red',
    'silverGray',
  ],
  facialHair: [
    'none',
    'beardLight',
    'beardMagestic',
    'beardMedium',
    'mustacheFancy',
    'mustacheMagnum',
  ],
  clothes: [
    'blazerAndShirt',
    'blazerAndSweater',
    'collarAndSweater',
    'graphicShirt',
    'hoodie',
    'overall',
    'shirtCrewNeck',
    'shirtScoopNeck',
    'shirtVNeck',
  ],
  eyes: [
    'close',
    'cry',
    'default',
    'dizzy',
    'eyeRoll',
    'happy',
    'hearts',
    'side',
    'squint',
    'surprised',
    'wink',
    'winkWacky',
  ],
  eyebrow: [
    'angry',
    'angryNatural',
    'default',
    'defaultNatural',
    'flatNatural',
    'raisedExcited',
    'raisedExcitedNatural',
    'sadConcerned',
    'sadConcernedNatural',
    'unibrowNatural',
    'upDown',
    'upDownNatural',
  ],
  mouth: [
    'concerned',
    'default',
    'disbelief',
    'eating',
    'grimace',
    'sad',
    'scream',
    'serious',
    'smile',
    'tongue',
    'twinkle',
    'vomit',
  ],
  skinColor: [
    'tanned',
    'yellow',
    'pale',
    'light',
    'brown',
    'darkBrown',
    'black',
  ],
};

export const AVATAR_LABELS: { [key: string]: string } = {
  top: 'Head',
  accessories: 'Accessories',
  hairColor: 'Hair Color',
  facialHair: 'Facial Hair',
  clothes: 'Clothes',
  eyes: 'Eyes',
  eyebrow: 'Eyebrows',
  mouth: 'Mouth',
  skinColor: 'Skin',
};
